services:
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:${VERSION}
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
            - /etc/cloudflare/origin-server-certificates/edouardq.fr:/etc/ssl/certs
        environment:
            SSL_CERT: "/etc/ssl/certs/cert.pem"
            SSL_KEY: "/etc/ssl/certs/privkey.pem"
        networks:
            - cloudflare

        
       
volumes:
    portainer_data:

networks:
    cloudflare:
        external: true
